export const sliders = [
    {
        sliderType: "line",
        minValue: 65,
        maxValue: 180,
        alignment: "horizontal",
        name: "Grab",
        value: 135,
    },
    {
        sliderType: "line",
        minValue: 90,
        maxValue: 180,
        alignment: "horizontal",
        name: "Elbow",
        value: 135,
    },
    {
        sliderType: "circle",
        minValue: 0,
        maxValue: 180,
        alignment: "horizontal",
        name: "Rotate wrist",
        value: 90,
    },
    {
        sliderType: "line",
        minValue: 0,
        maxValue: 180,
        alignment: "vertrical",
        name: "Vertical wrist",
        value: 90,
    },
    {
        sliderType: "line",
        minValue: 0,
        maxValue: 360,
        alignment: "horizontal",
        name: "Bicep",
        value: 0,
    },
    {
        sliderType: "circle",
        minValue: 0,
        maxValue: 999,
        alignment: "horizontal",
        name: "Shoulder",
        value: 0,
    }
];
